String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'vanilla birthday',
    '%4'                    : 'bubblegum pink',
    '%8'                    : 'sunshine vanilla',
    '%16'                   : 'valrhona blonde ganache',
    '%32'                   : 'chocolare peanut butter cheesecake',
    '%64'                   : 'chocolate mint fudge',
    '%128'                  : 'chocolate spider web',
    '%256'                  : 'toasted marshmallow',
    '%512'                  : 'cookies and creme',
    '%1024'                 : 'chocolate sundae',
    '%2048'                 : 'white chocolate peppermint',
    '%4096'                 : '2017 Confetti Vanilla',
    '%8192'                 : 'Rainbow',
    '%p0'                   : '0 or 2 points',
    '%p4'                   : '4 points',
    '%p8'                   : '8 points',
    '%p16'                  : '16 points',
    '%p32'                  : '32 points',
    '%p64'                  : '64 points',
    '%p128'                 : '128 points',
    '%p256'                 : '256 points',
    '%p512'                 : '512 points',
    '%p1024'                : '1024 points',
    '%p2048'                : '2048 points',
    '%p4096'                : '4096 points',
    '%p8192'                : '8192 points'

	},

  "en": {
    "%game-intro"           : "Join the <strong>Custom Tiles!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"https://2048-CUSTOM.rithvik-kona152.repl.co\">2048-CUSTOM</a> is a spin-off of the official version of <a href=\"https://play2048.co\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "images by <a href=\"http://www.quest.eb.com/\" title=\"Brittanica Imagequest\">Brittanica ImageQuest</a>.",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : '0 points on its own, most basic thing E V E R',
    '%4'                    : '4 points, hey you figured out A R R O W K E Y S',
    '%8'                    : '8 points, easy to do this through spamming',
    '%16'                   : '16 points, still easy to do this through spamming',
    '%32'                   : '32 points, a bit more unlikely to get through spamming, but still ez',
    '%64'                   : '64 points, might get this through spamming',
    '%128'                  : '128 points, you know how to play decently well',
    '%256'                  : '256 points, you know how to play decently well',
    '%512'                  : '512 points, you know how to play decently well',
    '%1024'                 : '1024 points, you know how to play really well',
    '%2048'                 : '2048 points, the namesake of the game',
    '%4096'                 : '4096 points, very high',
    '%8192'                 : '8192 points, you must be a G O D at this game to acheive this',
    '%p0'                   : '2 (unmerged, 0) points',
    '%p4'                   : '4 points',
    '%p8'                   : '8 points',
    '%p16'                  : '16 points',
    '%p32'                  : '32 points',
    '%p64'                  : '64 points',
    '%p128'                 : '128 points',
    '%p256'                 : '256 points',
    '%p512'                 : '512 points',
    '%p1024'                : '1024 points',
    '%p2048'                : '2048 points',
    '%p4096'                : '4096 points',
    '%p8192'                : '8192 points'
  }

});
